# Generated by Django 4.2.4 on 2023-09-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_reserv'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Запросы на связи', 'verbose_name_plural': 'Запросы на связь'},
        ),
        migrations.RemoveField(
            model_name='reserv',
            name='email',
        ),
        migrations.AddField(
            model_name='reserv',
            name='date',
            field=models.CharField(default=1, max_length=255, verbose_name='Дата'),
            preserve_default=False,
        ),
    ]
