# Generated by Django 4.2.4 on 2023-09-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserv',
            name='message',
            field=models.TextField(default=1, verbose_name='Сообщение'),
            preserve_default=False,
        ),
    ]
