# Generated by Django 4.2.4 on 2023-11-13 21:46

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0004_remove_list_image_list_image_one_list_image_two'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='gallery/', verbose_name='фотография'),
        ),
        migrations.AlterField(
            model_name='list',
            name='image_one',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='price/', verbose_name='Первая фотография'),
        ),
        migrations.AlterField(
            model_name='list',
            name='image_two',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='price/', verbose_name='Первая фотография'),
        ),
    ]
