# Generated by Django 4.2.4 on 2023-09-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_founder'),
    ]

    operations = [
        migrations.AddField(
            model_name='founder',
            name='descriptions_one',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='founder',
            name='descriptions_three',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='founder',
            name='descriptions_two',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
