# Generated by Django 4.2.4 on 2023-11-13 21:46

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_founder_descriptions_one_founder_descriptions_three_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founder',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='founder/', verbose_name='Фотография'),
        ),
    ]
