# Generated by Django 4.2.4 on 2023-08-23 08:20

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='video/', verbose_name='Фотография для баннера')),
                ('title', models.CharField(max_length=255, verbose_name='Название видео')),
                ('url', models.URLField(verbose_name='Ссылка на видео')),
            ],
            options={
                'verbose_name': 'Видео о MerriGarden',
                'verbose_name_plural': 'Видео о MerriGarden',
            },
        ),
    ]
