# Generated by Django 4.2.4 on 2023-09-10 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
