# Generated by Django 4.2.4 on 2023-09-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_delete_about_delete_news_delete_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='descriptions_contacts',
            field=models.TextField(blank=True, null=True, verbose_name="Описание для страницы 'Контакты' "),
        ),
    ]
